### ISSUE TITLE
how can i contact you bought a bot from you

### ISSUE THREAD

**Issue by tireder** [AsepctDEVS/AsepctDEVS#3]
how can i contact you bought a bot from you

**Comment by KillaNAdev** [comment]
Please quit messaging me on serval places like I said you can message me on discord by spilt#4000 I have sent you your product my discord was deleted. I don't see the point in making a Paypal dispute.

**Comment by tireder** [comment]
spilt#4000 doesn't exist

**Comment by KillaNAdev** [comment]
it does tho 💀

**Comment by KillaNAdev** [comment]
![image](https://user-images.githubusercontent.com/90366824/159576434-f4ffd4c0-0596-41e8-8065-3add66e346bc.png)

**Comment by tireder** [comment]
![Uploading Screenshot_20220323-134401_Discord.jpg…]()

**Comment by tireder** [comment]
Nah dog

**Comment by tireder** [comment]
![Screenshot_20220323-134401_Discord](https://user-images.githubusercontent.com/42284777/160091077-6750ebde-ce55-450b-8fa6-59681d81e407.jpg)

**Comment by KillaNAdev** [comment]
ur discord is broken then

**Comment by tireder** [comment]
I tried with another discord same output

**Comment by tireder** [comment]
Tried with 2 different discords
